/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Insurance;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author alinb
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    int pX,pY;
    public Admin() {
        initComponents();
        UIManager.put("OptionPane.background",new java.awt.Color(0,153,0));
        UIManager.put("Button.select",new ColorUIResource(new Color(0, 0, 0, 0)));
        UIManager.put("Panel.background",new java.awt.Color(0,153,0));
        UIManager.put("Button.background",Color.BLACK);
        UIManager.put("Button.foreground",new java.awt.Color(0,153,0));
        UIManager.put("Button.focus",new ColorUIResource(new Color(0, 0, 0, 0)));
        UIManager.put("Button.rollover",false); 
        UIManager.put("Button.defaultButtonFollowsFocus ",false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deleteagent = new javax.swing.JButton();
        addagent = new javax.swing.JButton();
        min = new javax.swing.JPanel();
        mini3 = new javax.swing.JLabel();
        exit = new javax.swing.JPanel();
        exit3 = new javax.swing.JLabel();
        viewagent = new javax.swing.JButton();
        editagent = new javax.swing.JButton();
        signout = new javax.swing.JButton();
        home = new javax.swing.JPanel();
        welcome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ephone = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        eclear = new javax.swing.JButton();
        update = new javax.swing.JButton();
        eaddress = new javax.swing.JTextArea();
        eerror = new javax.swing.JLabel();
        view = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vname = new javax.swing.JLabel();
        vphoneno = new javax.swing.JLabel();
        vaddress = new javax.swing.JTextArea();
        add = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        adphone = new javax.swing.JTextField();
        adname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        adclear = new javax.swing.JButton();
        adadd = new javax.swing.JButton();
        adaddress = new javax.swing.JTextArea();
        delete = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        bdelete = new javax.swing.JButton();
        dclear = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        changeapass = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        newapass = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        newapass1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        aerror = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        changecpass = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        newcpass = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        newcpass1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cerror = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cpassword = new javax.swing.JButton();
        cpassword1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("1177326-5011.png")));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(838, 511));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINSTRATOR ");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(320, 40, 220, 30);

        deleteagent.setBackground(new java.awt.Color(255, 255, 255));
        deleteagent.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        deleteagent.setForeground(new java.awt.Color(102, 102, 102));
        deleteagent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Delete Document-15.png"))); // NOI18N
        deleteagent.setText("  DELETE AGENT");
        deleteagent.setBorderPainted(false);
        deleteagent.setFocusPainted(false);
        deleteagent.setFocusable(false);
        deleteagent.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        deleteagent.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        deleteagent.setMargin(new java.awt.Insets(2, 20, 2, 0));
        deleteagent.setRequestFocusEnabled(false);
        deleteagent.setRolloverEnabled(false);
        deleteagent.setVerifyInputWhenFocusTarget(false);
        deleteagent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteagentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteagentMouseExited(evt);
            }
        });
        deleteagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteagentActionPerformed(evt);
            }
        });
        jPanel3.add(deleteagent);
        deleteagent.setBounds(0, 250, 200, 50);

        addagent.setBackground(new java.awt.Color(255, 255, 255));
        addagent.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        addagent.setForeground(new java.awt.Color(102, 102, 102));
        addagent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Add Property-15.png"))); // NOI18N
        addagent.setText("  ADD AGENT");
        addagent.setBorderPainted(false);
        addagent.setFocusPainted(false);
        addagent.setFocusable(false);
        addagent.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addagent.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addagent.setMargin(new java.awt.Insets(2, 20, 2, 0));
        addagent.setRequestFocusEnabled(false);
        addagent.setRolloverEnabled(false);
        addagent.setVerifyInputWhenFocusTarget(false);
        addagent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addagentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addagentMouseExited(evt);
            }
        });
        addagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addagentActionPerformed(evt);
            }
        });
        jPanel3.add(addagent);
        addagent.setBounds(0, 200, 200, 50);

        min.setBackground(new java.awt.Color(255, 255, 255));
        min.setForeground(new java.awt.Color(153, 153, 153));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });

        mini3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mini3.setForeground(new java.awt.Color(153, 153, 153));
        mini3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini3.setText("-");
        mini3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mini3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mini3MouseExited(evt);
            }
        });
        min.add(mini3);

        jPanel3.add(min);
        min.setBounds(780, 0, 30, 30);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        exit3.setBackground(new java.awt.Color(255, 255, 255));
        exit3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit3.setForeground(new java.awt.Color(153, 153, 153));
        exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit3MouseExited(evt);
            }
        });
        exit.add(exit3);

        jPanel3.add(exit);
        exit.setBounds(810, 0, 30, 30);

        viewagent.setBackground(new java.awt.Color(255, 255, 255));
        viewagent.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        viewagent.setForeground(new java.awt.Color(102, 102, 102));
        viewagent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Info-20.png"))); // NOI18N
        viewagent.setText("  VIEW AGENT INFO");
        viewagent.setBorderPainted(false);
        viewagent.setFocusPainted(false);
        viewagent.setFocusable(false);
        viewagent.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        viewagent.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        viewagent.setMargin(new java.awt.Insets(2, 20, 2, 0));
        viewagent.setRequestFocusEnabled(false);
        viewagent.setRolloverEnabled(false);
        viewagent.setVerifyInputWhenFocusTarget(false);
        viewagent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewagentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewagentMouseExited(evt);
            }
        });
        viewagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewagentActionPerformed(evt);
            }
        });
        jPanel3.add(viewagent);
        viewagent.setBounds(0, 100, 200, 50);

        editagent.setBackground(new java.awt.Color(255, 255, 255));
        editagent.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        editagent.setForeground(new java.awt.Color(102, 102, 102));
        editagent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Edit File-20.png"))); // NOI18N
        editagent.setText("  EDIT AGENT INFO");
        editagent.setBorderPainted(false);
        editagent.setFocusPainted(false);
        editagent.setFocusable(false);
        editagent.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        editagent.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        editagent.setMargin(new java.awt.Insets(2, 20, 2, 0));
        editagent.setRequestFocusEnabled(false);
        editagent.setRolloverEnabled(false);
        editagent.setVerifyInputWhenFocusTarget(false);
        editagent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editagentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editagentMouseExited(evt);
            }
        });
        editagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editagentActionPerformed(evt);
            }
        });
        jPanel3.add(editagent);
        editagent.setBounds(0, 150, 200, 50);

        signout.setBackground(new java.awt.Color(0, 153, 0));
        signout.setForeground(new java.awt.Color(51, 51, 51));
        signout.setText("Sign Out");
        signout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        signout.setFocusPainted(false);
        signout.setFocusable(false);
        signout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signout.setRequestFocusEnabled(false);
        signout.setRolloverEnabled(false);
        signout.setVerifyInputWhenFocusTarget(false);
        signout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        jPanel3.add(signout);
        signout.setBounds(710, 40, 90, 30);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setLayout(new java.awt.CardLayout());

        welcome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Adminstrator");

        javax.swing.GroupLayout welcomeLayout = new javax.swing.GroupLayout(welcome);
        welcome.setLayout(welcomeLayout);
        welcomeLayout.setHorizontalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        welcomeLayout.setVerticalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        home.add(welcome, "card6");

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setLayout(null);

        jComboBox2.setBackground(new java.awt.Color(0, 153, 0));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox2.setMaximumRowCount(50);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox2.setFocusable(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        edit.add(jComboBox2);
        jComboBox2.setBounds(233, 42, 161, 21);

        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Select agent key");
        edit.add(jLabel7);
        jLabel7.setBounds(233, 22, 161, 14);

        jLabel11.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("Name                            :");
        edit.add(jLabel11);
        jLabel11.setBounds(101, 118, 120, 22);

        jLabel12.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("Address                        :");
        edit.add(jLabel12);
        jLabel12.setBounds(101, 169, 120, 22);

        jLabel13.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("Phone number             :");
        edit.add(jLabel13);
        jLabel13.setBounds(100, 290, 130, 22);

        ephone.setForeground(new java.awt.Color(0, 153, 0));
        ephone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ephone.setCaretColor(new java.awt.Color(0, 153, 0));
        edit.add(ephone);
        ephone.setBounds(270, 290, 210, 20);

        ename.setForeground(new java.awt.Color(0, 153, 0));
        ename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ename.setCaretColor(new java.awt.Color(0, 153, 0));
        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        edit.add(ename);
        ename.setBounds(270, 120, 210, 20);

        eclear.setBackground(new java.awt.Color(0, 153, 0));
        eclear.setForeground(new java.awt.Color(51, 51, 51));
        eclear.setText("CLEAR");
        eclear.setFocusPainted(false);
        eclear.setFocusable(false);
        eclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eclearActionPerformed(evt);
            }
        });
        edit.add(eclear);
        eclear.setBounds(350, 350, 100, 30);

        update.setBackground(new java.awt.Color(0, 153, 0));
        update.setForeground(new java.awt.Color(51, 51, 51));
        update.setText("UPDATE");
        update.setFocusPainted(false);
        update.setFocusable(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        edit.add(update);
        update.setBounds(170, 350, 100, 30);

        eaddress.setColumns(20);
        eaddress.setForeground(new java.awt.Color(0, 153, 0));
        eaddress.setRows(5);
        eaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        eaddress.setCaretColor(new java.awt.Color(0, 153, 0));
        edit.add(eaddress);
        eaddress.setBounds(270, 170, 210, 92);

        eerror.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eerror.setForeground(new java.awt.Color(204, 0, 0));
        eerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.add(eerror);
        eerror.setBounds(0, 320, 640, 20);

        home.add(edit, "card2");

        view.setBackground(new java.awt.Color(255, 255, 255));
        view.setLayout(null);

        jComboBox1.setBackground(new java.awt.Color(0, 153, 0));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setMaximumRowCount(50);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        view.add(jComboBox1);
        jComboBox1.setBounds(233, 42, 161, 21);

        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Select agent key");
        view.add(jLabel4);
        jLabel4.setBounds(233, 22, 161, 14);

        jLabel5.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Name                            :");
        view.add(jLabel5);
        jLabel5.setBounds(101, 118, 120, 22);

        jLabel6.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Address                        :");
        view.add(jLabel6);
        jLabel6.setBounds(101, 169, 120, 22);

        jLabel8.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Phone number             :");
        view.add(jLabel8);
        jLabel8.setBounds(100, 280, 130, 22);

        vname.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        vname.setForeground(new java.awt.Color(0, 153, 0));
        view.add(vname);
        vname.setBounds(260, 120, 210, 20);

        vphoneno.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        vphoneno.setForeground(new java.awt.Color(0, 153, 0));
        view.add(vphoneno);
        vphoneno.setBounds(260, 280, 230, 20);

        vaddress.setColumns(20);
        vaddress.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        vaddress.setForeground(new java.awt.Color(0, 153, 0));
        vaddress.setRows(5);
        view.add(vaddress);
        vaddress.setBounds(260, 170, 230, 90);

        home.add(view, "card3");

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("Name                            :");
        add.add(jLabel15);
        jLabel15.setBounds(100, 100, 120, 22);

        jLabel16.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 0));
        jLabel16.setText("Address                        :");
        add.add(jLabel16);
        jLabel16.setBounds(100, 150, 120, 22);

        jLabel14.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("Phone number             :");
        add.add(jLabel14);
        jLabel14.setBounds(100, 270, 130, 22);

        adphone.setForeground(new java.awt.Color(0, 153, 0));
        adphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        adphone.setCaretColor(new java.awt.Color(0, 153, 0));
        adphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adphoneActionPerformed(evt);
            }
        });
        add.add(adphone);
        adphone.setBounds(270, 270, 230, 20);

        adname.setForeground(new java.awt.Color(0, 153, 0));
        adname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        adname.setCaretColor(new java.awt.Color(0, 153, 0));
        adname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adnameActionPerformed(evt);
            }
        });
        add.add(adname);
        adname.setBounds(270, 100, 230, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ADD NEW AGENT");
        add.add(jLabel17);
        jLabel17.setBounds(220, 30, 220, 30);

        adclear.setBackground(new java.awt.Color(0, 153, 0));
        adclear.setForeground(new java.awt.Color(51, 51, 51));
        adclear.setText("CLEAR");
        adclear.setFocusPainted(false);
        adclear.setFocusable(false);
        adclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adclearActionPerformed(evt);
            }
        });
        add.add(adclear);
        adclear.setBounds(350, 350, 100, 30);

        adadd.setBackground(new java.awt.Color(0, 153, 0));
        adadd.setForeground(new java.awt.Color(51, 51, 51));
        adadd.setText("ADD");
        adadd.setFocusPainted(false);
        adadd.setFocusable(false);
        adadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaddActionPerformed(evt);
            }
        });
        add.add(adadd);
        adadd.setBounds(170, 350, 100, 30);

        adaddress.setColumns(20);
        adaddress.setForeground(new java.awt.Color(0, 153, 0));
        adaddress.setRows(5);
        adaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        adaddress.setCaretColor(new java.awt.Color(0, 153, 0));
        add.add(adaddress);
        adaddress.setBounds(270, 140, 230, 110);

        home.add(add, "card3");

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setLayout(null);

        jComboBox3.setBackground(new java.awt.Color(0, 153, 0));
        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox3.setMaximumRowCount(50);
        jComboBox3.setFocusable(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        delete.add(jComboBox3);
        jComboBox3.setBounds(240, 160, 161, 21);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Select agent key");
        delete.add(jLabel18);
        jLabel18.setBounds(230, 130, 180, 20);

        bdelete.setBackground(new java.awt.Color(0, 153, 0));
        bdelete.setForeground(new java.awt.Color(51, 51, 51));
        bdelete.setText("DELETE");
        bdelete.setFocusPainted(false);
        bdelete.setFocusable(false);
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        delete.add(bdelete);
        bdelete.setBounds(170, 230, 100, 30);

        dclear.setBackground(new java.awt.Color(0, 153, 0));
        dclear.setForeground(new java.awt.Color(51, 51, 51));
        dclear.setText("CLEAR");
        dclear.setFocusPainted(false);
        dclear.setFocusable(false);
        dclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dclearActionPerformed(evt);
            }
        });
        delete.add(dclear);
        dclear.setBounds(360, 230, 100, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("DELETE AGENT");
        delete.add(jLabel19);
        jLabel19.setBounds(0, 30, 640, 30);

        home.add(delete, "card3");

        changeapass.setBackground(new java.awt.Color(255, 255, 255));
        changeapass.setLayout(null);

        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Re-type password");
        changeapass.add(jLabel9);
        jLabel9.setBounds(230, 220, 190, 29);

        newapass.setForeground(new java.awt.Color(0, 153, 0));
        newapass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        newapass.setCaretColor(new java.awt.Color(0, 153, 0));
        changeapass.add(newapass);
        newapass.setBounds(230, 150, 190, 33);

        jLabel24.setForeground(new java.awt.Color(0, 153, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("New Password");
        changeapass.add(jLabel24);
        jLabel24.setBounds(230, 120, 190, 29);

        newapass1.setForeground(new java.awt.Color(0, 153, 0));
        newapass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        newapass1.setCaretColor(new java.awt.Color(0, 153, 0));
        changeapass.add(newapass1);
        newapass1.setBounds(230, 250, 190, 33);

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("RESET");
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        changeapass.add(jButton1);
        jButton1.setBounds(130, 330, 146, 37);

        jComboBox4.setBackground(new java.awt.Color(0, 153, 0));
        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox4.setMaximumRowCount(50);
        jComboBox4.setFocusable(false);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        changeapass.add(jComboBox4);
        jComboBox4.setBounds(240, 70, 161, 21);

        jLabel20.setForeground(new java.awt.Color(0, 153, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Select agent key");
        changeapass.add(jLabel20);
        jLabel20.setBounds(240, 50, 161, 14);

        aerror.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        aerror.setForeground(new java.awt.Color(255, 0, 0));
        aerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeapass.add(aerror);
        aerror.setBounds(0, 294, 640, 30);

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("CLEAR");
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        changeapass.add(jButton4);
        jButton4.setBounds(380, 330, 146, 37);

        home.add(changeapass, "card3");

        changecpass.setBackground(new java.awt.Color(255, 255, 255));
        changecpass.setLayout(null);

        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Re-type password");
        changecpass.add(jLabel10);
        jLabel10.setBounds(230, 200, 190, 29);

        newcpass.setForeground(new java.awt.Color(0, 153, 0));
        newcpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        newcpass.setCaretColor(new java.awt.Color(0, 153, 0));
        changecpass.add(newcpass);
        newcpass.setBounds(230, 150, 190, 33);

        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("New Password");
        changecpass.add(jLabel25);
        jLabel25.setBounds(230, 120, 190, 29);

        newcpass1.setForeground(new java.awt.Color(0, 153, 0));
        newcpass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        newcpass1.setCaretColor(new java.awt.Color(0, 153, 0));
        newcpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcpass1ActionPerformed(evt);
            }
        });
        changecpass.add(newcpass1);
        newcpass1.setBounds(230, 230, 190, 33);

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("RESET");
        jButton3.setAutoscrolls(true);
        jButton3.setFocusCycleRoot(true);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setInheritsPopupMenu(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        changecpass.add(jButton3);
        jButton3.setBounds(120, 320, 146, 37);

        jComboBox5.setBackground(new java.awt.Color(0, 153, 0));
        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox5.setMaximumRowCount(50);
        jComboBox5.setFocusable(false);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        changecpass.add(jComboBox5);
        jComboBox5.setBounds(250, 70, 161, 21);

        jLabel21.setForeground(new java.awt.Color(0, 153, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Select policy holder key");
        changecpass.add(jLabel21);
        jLabel21.setBounds(250, 50, 161, 14);

        cerror.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        cerror.setForeground(new java.awt.Color(255, 0, 0));
        cerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changecpass.add(cerror);
        cerror.setBounds(0, 284, 640, 20);

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("CLEAR");
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        changecpass.add(jButton5);
        jButton5.setBounds(380, 320, 146, 37);

        home.add(changecpass, "card3");

        jPanel3.add(home);
        home.setBounds(200, 100, 640, 410);

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Home Page-20.png"))); // NOI18N
        jButton2.setText("Home");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        jButton2.setVerifyInputWhenFocusTarget(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(40, 40, 110, 30);

        cpassword.setBackground(new java.awt.Color(255, 255, 255));
        cpassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cpassword.setForeground(new java.awt.Color(102, 102, 102));
        cpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Password Reset-20.png"))); // NOI18N
        cpassword.setText(" RESET CLIENT PASSWORD");
        cpassword.setBorderPainted(false);
        cpassword.setFocusPainted(false);
        cpassword.setFocusable(false);
        cpassword.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        cpassword.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cpassword.setMargin(new java.awt.Insets(2, 20, 2, 0));
        cpassword.setRequestFocusEnabled(false);
        cpassword.setRolloverEnabled(false);
        cpassword.setVerifyInputWhenFocusTarget(false);
        cpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cpasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cpasswordMouseExited(evt);
            }
        });
        cpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpasswordActionPerformed(evt);
            }
        });
        jPanel3.add(cpassword);
        cpassword.setBounds(0, 350, 200, 50);

        cpassword1.setBackground(new java.awt.Color(255, 255, 255));
        cpassword1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cpassword1.setForeground(new java.awt.Color(102, 102, 102));
        cpassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Password Reset-20.png"))); // NOI18N
        cpassword1.setText("  RESET AGENT PASSWORD");
        cpassword1.setBorderPainted(false);
        cpassword1.setFocusPainted(false);
        cpassword1.setFocusable(false);
        cpassword1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        cpassword1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cpassword1.setMargin(new java.awt.Insets(2, 20, 2, 0));
        cpassword1.setRequestFocusEnabled(false);
        cpassword1.setRolloverEnabled(false);
        cpassword1.setVerifyInputWhenFocusTarget(false);
        cpassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cpassword1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cpassword1MouseExited(evt);
            }
        });
        cpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassword1ActionPerformed(evt);
            }
        });
        jPanel3.add(cpassword1);
        cpassword1.setBounds(0, 300, 200, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 840, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addagentActionPerformed
        home.removeAll();
        home.add(add);
        home.repaint();
        home.revalidate();
        viewagent.setForeground(new java.awt.Color(102,102,102));
        deleteagent.setForeground(new java.awt.Color(102,102,102));
        editagent.setForeground(new java.awt.Color(102,102,102));
        addagent.setForeground(new java.awt.Color(0,153,0));
        cpassword1.setForeground(new java.awt.Color(102,102,102));
        cpassword.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_addagentActionPerformed

    private void mini3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseClicked
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_mini3MouseClicked

    private void mini3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseEntered
        min.setBackground(Color.LIGHT_GRAY);
        mini3.setForeground(Color.BLACK);
    }//GEN-LAST:event_mini3MouseEntered

    private void mini3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseExited
        min.setBackground(Color.WHITE);
        mini3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_mini3MouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        min.setBackground(Color.LIGHT_GRAY);
        mini3.setForeground(Color.BLACK);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        min.setBackground(Color.WHITE);
        mini3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_minMouseExited

    private void exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit3MouseClicked

    private void exit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseEntered
        exit.setBackground(Color.RED);
        exit3.setForeground(Color.WHITE);
    }//GEN-LAST:event_exit3MouseEntered

    private void exit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseExited
        exit.setBackground(Color.WHITE);
        exit3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_exit3MouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.RED);
        exit3.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(Color.WHITE);
        exit3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_exitMouseExited

    @SuppressWarnings("ConvertToTryWithResources")
    private void editagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editagentActionPerformed
        try {
            home.removeAll();
            home.add(edit);
            home.repaint();
            home.revalidate();
            viewagent.setForeground(new java.awt.Color(102,102,102));
            deleteagent.setForeground(new java.awt.Color(102,102,102));
            editagent.setForeground(new java.awt.Color(0,153,0));
            addagent.setForeground(new java.awt.Color(102,102,102));
            cpassword1.setForeground(new java.awt.Color(102,102,102));
            cpassword.setForeground(new java.awt.Color(102,102,102));
            jComboBox2.removeAllItems();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("select agentkey from agent");
            ResultSet rs=pst.executeQuery();
            jComboBox2.addItem("Select");
            while(rs.next()){
                jComboBox2.addItem(rs.getString(1));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editagentActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(getLocation().x + evt.getX() - pX,getLocation().y + evt.getY() - pY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       pX = evt.getX();
       pY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        Login.main(new String[0]);
        dispose();        
    }//GEN-LAST:event_signoutActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void viewagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewagentActionPerformed
        try {
            home.removeAll();
            home.add(view);
            home.repaint();
            home.revalidate();
            viewagent.setForeground(new java.awt.Color(0,153,0));
            deleteagent.setForeground(new java.awt.Color(102,102,102));
            editagent.setForeground(new java.awt.Color(102,102,102));
            addagent.setForeground(new java.awt.Color(102,102,102));
            cpassword1.setForeground(new java.awt.Color(102,102,102));
            cpassword.setForeground(new java.awt.Color(102,102,102));
            jComboBox1.removeAllItems();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("select agentkey from agent");
            ResultSet rs=pst.executeQuery();
            jComboBox1.addItem("Select");
            while(rs.next()){
                jComboBox1.addItem(rs.getString(1));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewagentActionPerformed
   
    @SuppressWarnings("ConvertToTryWithResources")
    private void deleteagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteagentActionPerformed
        try {
            home.removeAll();
            home.add(delete);
            home.repaint();
            home.revalidate();
            viewagent.setForeground(new java.awt.Color(102,102,102));
            deleteagent.setForeground(new java.awt.Color(0,153,0));
            editagent.setForeground(new java.awt.Color(102,102,102));
            addagent.setForeground(new java.awt.Color(102,102,102));
            cpassword.setForeground(new java.awt.Color(102,102,102));
            cpassword1.setForeground(new java.awt.Color(102,102,102));
            jComboBox3.removeAllItems();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("select agentkey from agent");
            ResultSet rs=pst.executeQuery();
            jComboBox3.addItem("Select");
            while(rs.next()){
                jComboBox3.addItem(rs.getString(1));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deleteagentActionPerformed

    private void editagentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editagentMouseEntered
        editagent.setBackground(Color.lightGray);
    }//GEN-LAST:event_editagentMouseEntered

    private void editagentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editagentMouseExited
        editagent.setBackground(Color.WHITE);
    }//GEN-LAST:event_editagentMouseExited

    private void viewagentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewagentMouseEntered
        viewagent.setBackground(Color.lightGray);
    }//GEN-LAST:event_viewagentMouseEntered

    private void viewagentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewagentMouseExited
        viewagent.setBackground(Color.WHITE);
    }//GEN-LAST:event_viewagentMouseExited

    private void addagentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addagentMouseEntered
        addagent.setBackground(Color.lightGray);
    }//GEN-LAST:event_addagentMouseEntered

    private void addagentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addagentMouseExited
        addagent.setBackground(Color.WHITE);
    }//GEN-LAST:event_addagentMouseExited

    private void deleteagentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteagentMouseEntered
        deleteagent.setBackground(Color.lightGray);
    }//GEN-LAST:event_deleteagentMouseEntered

    private void deleteagentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteagentMouseExited
        deleteagent.setBackground(Color.WHITE);
    }//GEN-LAST:event_deleteagentMouseExited

    @SuppressWarnings("ConvertToTryWithResources")
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if(jComboBox1.getSelectedItem()=="Select") {
           vname.setText("");
           vaddress.setText("");
           vphoneno.setText(""); 
        }
        try {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("select aname,address,phone from agent where agentkey=?");
            pst.setString(1, (String) jComboBox1.getSelectedItem());
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                vname.setText(rs.getString(1));
                vaddress.setText(rs.getString(2));
                vphoneno.setText(Long.toString(rs.getLong(3)));
            }
            pst.close();
            conn.close();
    }//GEN-LAST:event_jComboBox1ActionPerformed
        catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    @SuppressWarnings("ConvertToTryWithResources")
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        try {
            eerror.setText("");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement  pst = conn.prepareStatement("select aname,address,phone from agent where agentkey=?");
            pst.setString(1, (String) jComboBox2.getSelectedItem());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                ename.setText(rs.getString(1));
                eaddress.setText(rs.getString(2));
                ephone.setText(Long.toString(rs.getLong(3)));
            }
            pst.close();
            conn.close();
    }                                          
        catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    private void eclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eclearActionPerformed
        ename.setText("");
        eaddress.setText("");
        ephone.setText("");
        eerror.setText("");
        jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_eclearActionPerformed

    private void adnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adnameActionPerformed

    private void adphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adphoneActionPerformed

    private void adclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adclearActionPerformed
        adname.setText("");
        adaddress.setText("");
        adphone.setText("");
    }//GEN-LAST:event_adclearActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    @SuppressWarnings({"DeadBranch", "static-access"})
    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        try {
            if(!"Select".equals((String) jComboBox3.getSelectedItem())) {
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
                PreparedStatement  pst = conn.prepareStatement("delete from agent where agentkey=?");
                pst.setString(1, (String) jComboBox3.getSelectedItem());
                String msg = "Do you want to delete "+(String) jComboBox3.getSelectedItem();
                int n = JOptionPane.showConfirmDialog(delete, msg,"Delete",JOptionPane.YES_NO_OPTION);
                if(n==JOptionPane.YES_OPTION) {
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Sucessfully deleted "+(String) jComboBox3.getSelectedItem());
                    jComboBox3.removeAllItems();
                    pst = conn.prepareStatement("select agentkey from agent");
                    ResultSet rs=pst.executeQuery();
                    jComboBox3.addItem("Select");
                    while(rs.next()){
                        jComboBox3.addItem(rs.getString(1));
                    }
                    pst.close();
                    conn.close();
                }
                else {
                    jComboBox3.setSelectedIndex(0);
                    pst.close();
                    conn.close();
                }       
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void dclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dclearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        home.removeAll();
        home.add(welcome);
        home.repaint();
        home.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void adaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaddActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("insert into agent(agentkey,aname,address,phone,password)values(?,?,?,?,?)");
            String alphabet= "0123456789";
            String s = "A";
            Random random = new Random();
            int randomLen = 5;
            for (int i = 1; i < randomLen; i++) {
                char  c = alphabet.charAt(random.nextInt(10));
                s+=c;
            }
            pst.setString(1,s);
            pst.setString(2,adname.getText());
            pst.setString(3,adaddress.getText());
            pst.setLong(4,Long.parseLong(adphone.getText()));
            pst.setString(5,"welcome");
            pst.executeUpdate();
            String msg = "Sucessfully added\n Agent Key:"+s+"\nDefault password is 'welcome'";
            JOptionPane.showMessageDialog(null,msg);
            pst.close();
            conn.close();  
            adname.setText("");
            adaddress.setText("");
            adphone.setText("");
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_adaddActionPerformed

    private void cpasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpasswordMouseEntered
        cpassword.setBackground(Color.lightGray);
    }//GEN-LAST:event_cpasswordMouseEntered

    private void cpasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpasswordMouseExited
        cpassword.setBackground(Color.WHITE);
    }//GEN-LAST:event_cpasswordMouseExited

    @SuppressWarnings("ConvertToTryWithResources")
    private void cpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasswordActionPerformed
        try {
            home.removeAll();
            home.add(changecpass);
            home.repaint();
            home.revalidate();
            viewagent.setForeground(new java.awt.Color(102,102,102));
            deleteagent.setForeground(new java.awt.Color(102,102,102));
            editagent.setForeground(new java.awt.Color(102,102,102));
            addagent.setForeground(new java.awt.Color(102,102,102));
            cpassword.setForeground(new java.awt.Color(0,153,0));
            cpassword1.setForeground(new java.awt.Color(102,102,102));
            jComboBox5.removeAllItems();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("select phkey from policyholder");
            ResultSet rs=pst.executeQuery();
            jComboBox5.addItem("Select");
            while(rs.next()){
                jComboBox5.addItem(rs.getString(1));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cpasswordActionPerformed

    private void cpassword1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpassword1MouseEntered
        cpassword1.setBackground(Color.lightGray);
    }//GEN-LAST:event_cpassword1MouseEntered

    private void cpassword1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpassword1MouseExited
        cpassword1.setBackground(Color.WHITE);
    }//GEN-LAST:event_cpassword1MouseExited

    @SuppressWarnings("ConvertToTryWithResources")
    private void cpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassword1ActionPerformed
        try {
            home.removeAll();
            home.add(changeapass);
            home.repaint();
            home.revalidate();
            viewagent.setForeground(new java.awt.Color(102,102,102));
            deleteagent.setForeground(new java.awt.Color(102,102,102));
            editagent.setForeground(new java.awt.Color(102,102,102));
            addagent.setForeground(new java.awt.Color(102,102,102));
            cpassword1.setForeground(new java.awt.Color(0,153,0));
            cpassword.setForeground(new java.awt.Color(102,102,102));
            jComboBox4.removeAllItems();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("select agentkey from agent");
            ResultSet rs=pst.executeQuery();
            jComboBox4.addItem("Select");
            while(rs.next()){
                jComboBox4.addItem(rs.getString(1));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cpassword1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if("".equals(newcpass.getText()) || "".equals(newcpass1.getText())) {
                cerror.setText("Select any agent");
            }
            else {
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
                PreparedStatement pst = conn.prepareStatement("update policyholder set password=? where phkey=?");
                if(newcpass.getText().equals(newcpass1.getText())) {
                    pst.setString(1,newcpass1.getText());
                    pst.setString(2, (String) jComboBox5.getSelectedItem());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Password reset sucessfull");
                    newcpass.setText("");
                    newcpass1.setText("");
                    jComboBox5.setSelectedIndex(0);
                    pst.close();
                    conn.close();
                }
                else {
                    cerror.setText("Password doesn't match");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            if("".equals(ename.getText()) || "".equals(eaddress.getText()) || "".equals(ephone.getText())) {
                eerror.setText("Select any agent");
            }
            else {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("update agent set aname=?,address=?,phone=? where agentkey=?");
            pst.setString(1,ename.getText());
            pst.setString(2,eaddress.getText());
            pst.setLong(3,Long.parseLong(ephone.getText()));
            pst.setString(4, (String) jComboBox2.getSelectedItem());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Sucessfully Updated");
            
            ename.setText("");
            eaddress.setText("");
            ephone.setText("");
            jComboBox2.setSelectedIndex(0);
            pst.close();
            conn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
            if("".equals(newapass.getText()) || "".equals(newapass1.getText())) {
                aerror.setText("Select any agent");
            }
            else {
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
                PreparedStatement pst = conn.prepareStatement("update agent set password=? where agentkey=?");
                if(newapass.getText().equals(newapass1.getText())) {
                    pst.setString(1,newapass1.getText());
                    pst.setString(2, (String) jComboBox4.getSelectedItem());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Password reset sucessfull");
                    newapass.setText("");
                    newapass1.setText("");
                    jComboBox4.setSelectedIndex(0);
                    pst.close();
                    conn.close();
                }
                else {
                    aerror.setText("Password doesn't match");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newcpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newcpass1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        if(jComboBox5.getSelectedIndex()==0){
            newcpass.setText("");
            newcpass1.setText("");
            cerror.setText("");
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        if(jComboBox4.getSelectedIndex()==0){
            newapass.setText("");
            newapass1.setText("");
            aerror.setText("");
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        newapass.setText("");
        newapass1.setText("");
        aerror.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        newcpass.setText("");
        newcpass1.setText("");
        cerror.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MetroUI".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adadd;
    private javax.swing.JTextArea adaddress;
    private javax.swing.JButton adclear;
    private javax.swing.JPanel add;
    private javax.swing.JButton addagent;
    private javax.swing.JTextField adname;
    private javax.swing.JTextField adphone;
    private javax.swing.JLabel aerror;
    public javax.swing.JButton bdelete;
    private javax.swing.JLabel cerror;
    private javax.swing.JPanel changeapass;
    private javax.swing.JPanel changecpass;
    private javax.swing.JButton cpassword;
    private javax.swing.JButton cpassword1;
    private javax.swing.JButton dclear;
    private javax.swing.JPanel delete;
    private javax.swing.JButton deleteagent;
    private javax.swing.JTextArea eaddress;
    private javax.swing.JButton eclear;
    private javax.swing.JPanel edit;
    private javax.swing.JButton editagent;
    private javax.swing.JLabel eerror;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField ephone;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel exit3;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel min;
    private javax.swing.JLabel mini3;
    private javax.swing.JTextField newapass;
    private javax.swing.JPasswordField newapass1;
    private javax.swing.JTextField newcpass;
    private javax.swing.JPasswordField newcpass1;
    private javax.swing.JButton signout;
    private javax.swing.JButton update;
    private javax.swing.JTextArea vaddress;
    private javax.swing.JPanel view;
    private javax.swing.JButton viewagent;
    private javax.swing.JLabel vname;
    private javax.swing.JLabel vphoneno;
    private javax.swing.JPanel welcome;
    // End of variables declaration//GEN-END:variables
}
