/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Insurance;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alinb
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    int pX,pY;
    DefaultTableModel dm;
    public Client() {
        initComponents();
        clname.setText(Login.user); 
        UIManager.put("Button.select",Color.TRANSLUCENT);
        UIManager.put("OptionPane.background",new java.awt.Color(0,153,0));
        UIManager.put("Panel.background",new java.awt.Color(0,153,0));
        UIManager.put("Button.background",Color.BLACK);
        UIManager.put("Button.foreground",new java.awt.Color(0,153,0));
        UIManager.put("Button.focus",Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        welcome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clname = new javax.swing.JLabel();
        info = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        isex = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        iphkey = new javax.swing.JLabel();
        iphoneno = new javax.swing.JLabel();
        ipolicy = new javax.swing.JLabel();
        idob = new javax.swing.JLabel();
        iage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        iname = new javax.swing.JLabel();
        iaddress = new javax.swing.JTextArea();
        phedit = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ephone = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        eaddress = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        phsex = new javax.swing.JComboBox<>();
        update2 = new javax.swing.JButton();
        edob = new com.toedter.calendar.JDateChooser();
        cedit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ename1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        eaddress1 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        phsex1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        ephone1 = new javax.swing.JTextField();
        update1 = new javax.swing.JButton();
        update3 = new javax.swing.JButton();
        edob1 = new com.toedter.calendar.JDateChooser();
        policy = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pdbox = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pdpremium = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        pdcname = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pdkey = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        pdtype = new javax.swing.JLabel();
        changepass = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        newpass = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        newcpass1 = new javax.swing.JPasswordField();
        creset = new javax.swing.JButton();
        creset1 = new javax.swing.JButton();
        cerror = new javax.swing.JLabel();
        min = new javax.swing.JPanel();
        mini3 = new javax.swing.JLabel();
        exit = new javax.swing.JPanel();
        exit3 = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cpassword = new javax.swing.JButton();
        bpolicy = new javax.swing.JButton();
        bcedit = new javax.swing.JButton();
        bphedit = new javax.swing.JButton();
        binfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("1177326-5011.png")));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(838, 511));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLIENT");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(330, 40, 220, 30);

        home.setLayout(new java.awt.CardLayout());

        welcome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");

        clname.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        clname.setForeground(new java.awt.Color(0, 153, 0));
        clname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout welcomeLayout = new javax.swing.GroupLayout(welcome);
        welcome.setLayout(welcomeLayout);
        welcomeLayout.setHorizontalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeLayout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(clname, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
            .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(welcomeLayout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(141, Short.MAX_VALUE)))
        );
        welcomeLayout.setVerticalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(clname, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(welcomeLayout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );

        home.add(welcome, "card3");

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Policy holder key        :");
        info.add(jLabel5);
        jLabel5.setBounds(110, 40, 130, 22);

        jLabel6.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Address                        :");
        info.add(jLabel6);
        jLabel6.setBounds(110, 110, 120, 22);

        jLabel8.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Phone number              :");
        info.add(jLabel8);
        jLabel8.setBounds(110, 200, 130, 22);

        jLabel10.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setText("Policies Taken              :");
        info.add(jLabel10);
        jLabel10.setBounds(110, 330, 130, 22);

        jLabel11.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("DOB                                :");
        info.add(jLabel11);
        jLabel11.setBounds(110, 230, 130, 22);

        jLabel12.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("Sex                                  :");
        info.add(jLabel12);
        jLabel12.setBounds(110, 290, 130, 22);

        isex.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        isex.setForeground(new java.awt.Color(0, 153, 0));
        info.add(isex);
        isex.setBounds(260, 290, 210, 20);

        jLabel13.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("Age                                  :");
        info.add(jLabel13);
        jLabel13.setBounds(110, 260, 130, 22);

        iphkey.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        iphkey.setForeground(new java.awt.Color(0, 153, 0));
        info.add(iphkey);
        iphkey.setBounds(260, 40, 210, 20);

        iphoneno.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        iphoneno.setForeground(new java.awt.Color(0, 153, 0));
        info.add(iphoneno);
        iphoneno.setBounds(260, 200, 210, 20);

        ipolicy.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ipolicy.setForeground(new java.awt.Color(0, 153, 0));
        info.add(ipolicy);
        ipolicy.setBounds(260, 330, 210, 20);

        idob.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        idob.setForeground(new java.awt.Color(0, 153, 0));
        info.add(idob);
        idob.setBounds(260, 230, 210, 20);

        iage.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        iage.setForeground(new java.awt.Color(0, 153, 0));
        info.add(iage);
        iage.setBounds(260, 260, 210, 20);

        jLabel7.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("Name                            :");
        info.add(jLabel7);
        jLabel7.setBounds(110, 70, 120, 22);

        iname.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        iname.setForeground(new java.awt.Color(0, 153, 0));
        info.add(iname);
        iname.setBounds(260, 70, 210, 20);

        iaddress.setEditable(false);
        iaddress.setColumns(20);
        iaddress.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        iaddress.setForeground(new java.awt.Color(0, 153, 0));
        iaddress.setRows(5);
        iaddress.setCaretColor(new java.awt.Color(0, 153, 0));
        info.add(iaddress);
        iaddress.setBounds(260, 116, 230, 69);

        home.add(info, "card2");

        phedit.setBackground(new java.awt.Color(255, 255, 255));
        phedit.setForeground(new java.awt.Color(0, 153, 0));
        phedit.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("Name                            :");
        phedit.add(jLabel14);
        jLabel14.setBounds(100, 70, 120, 22);

        ename.setForeground(new java.awt.Color(0, 153, 0));
        ename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ename.setCaretColor(new java.awt.Color(0, 153, 0));
        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        phedit.add(ename);
        ename.setBounds(270, 70, 210, 20);

        jLabel15.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("Address                        :");
        phedit.add(jLabel15);
        jLabel15.setBounds(100, 110, 120, 22);

        jLabel16.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 0));
        jLabel16.setText("Phone number             :");
        phedit.add(jLabel16);
        jLabel16.setBounds(100, 280, 130, 22);

        ephone.setForeground(new java.awt.Color(0, 153, 0));
        ephone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ephone.setCaretColor(new java.awt.Color(0, 153, 0));
        phedit.add(ephone);
        ephone.setBounds(270, 280, 210, 20);

        update.setBackground(new java.awt.Color(0, 153, 0));
        update.setForeground(new java.awt.Color(51, 51, 51));
        update.setText("SAVE");
        update.setBorder(null);
        update.setFocusPainted(false);
        update.setFocusable(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        phedit.add(update);
        update.setBounds(170, 340, 100, 30);

        eaddress.setColumns(20);
        eaddress.setForeground(new java.awt.Color(0, 153, 0));
        eaddress.setRows(5);
        eaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        eaddress.setCaretColor(new java.awt.Color(0, 153, 0));
        phedit.add(eaddress);
        eaddress.setBounds(270, 110, 210, 70);

        jLabel17.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setText("DOB                                :");
        phedit.add(jLabel17);
        jLabel17.setBounds(100, 200, 130, 22);

        jLabel19.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 0));
        jLabel19.setText("Sex                                  :");
        phedit.add(jLabel19);
        jLabel19.setBounds(100, 240, 130, 22);

        phsex.setBackground(new java.awt.Color(0, 153, 0));
        phsex.setForeground(new java.awt.Color(51, 51, 51));
        phsex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        phsex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        phsex.setFocusable(false);
        phsex.setLightWeightPopupEnabled(false);
        phsex.setRequestFocusEnabled(false);
        phsex.setVerifyInputWhenFocusTarget(false);
        phedit.add(phsex);
        phsex.setBounds(270, 240, 110, 20);

        update2.setBackground(new java.awt.Color(0, 153, 0));
        update2.setForeground(new java.awt.Color(51, 51, 51));
        update2.setText("CLEAR");
        update2.setBorder(null);
        update2.setFocusPainted(false);
        update2.setFocusable(false);
        update2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update2ActionPerformed(evt);
            }
        });
        phedit.add(update2);
        update2.setBounds(350, 340, 100, 30);
        phedit.add(edob);
        edob.setBounds(270, 200, 210, 20);

        home.add(phedit, "card3");

        cedit.setBackground(new java.awt.Color(255, 255, 255));
        cedit.setLayout(null);

        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Select policy key");
        cedit.add(jLabel9);
        jLabel9.setBounds(233, 22, 161, 14);

        jComboBox2.setBackground(new java.awt.Color(0, 153, 0));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox2.setMaximumRowCount(50);
        jComboBox2.setBorder(null);
        jComboBox2.setFocusable(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        cedit.add(jComboBox2);
        jComboBox2.setBounds(233, 42, 161, 19);

        jLabel18.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 0));
        jLabel18.setText("Name                            :");
        cedit.add(jLabel18);
        jLabel18.setBounds(100, 90, 120, 22);

        ename1.setForeground(new java.awt.Color(0, 153, 0));
        ename1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ename1.setCaretColor(new java.awt.Color(0, 153, 0));
        ename1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ename1ActionPerformed(evt);
            }
        });
        cedit.add(ename1);
        ename1.setBounds(270, 90, 210, 20);

        jLabel20.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 0));
        jLabel20.setText("Address                        :");
        cedit.add(jLabel20);
        jLabel20.setBounds(100, 130, 120, 22);

        eaddress1.setColumns(20);
        eaddress1.setForeground(new java.awt.Color(0, 153, 0));
        eaddress1.setRows(5);
        eaddress1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        eaddress1.setCaretColor(new java.awt.Color(0, 153, 0));
        cedit.add(eaddress1);
        eaddress1.setBounds(270, 130, 210, 70);

        jLabel21.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 0));
        jLabel21.setText("DOB                                :");
        cedit.add(jLabel21);
        jLabel21.setBounds(100, 220, 130, 22);

        jLabel22.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 0));
        jLabel22.setText("Sex                                  :");
        cedit.add(jLabel22);
        jLabel22.setBounds(100, 260, 130, 22);

        phsex1.setBackground(new java.awt.Color(0, 153, 0));
        phsex1.setForeground(new java.awt.Color(51, 51, 51));
        phsex1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        phsex1.setFocusable(false);
        phsex1.setRequestFocusEnabled(false);
        phsex1.setVerifyInputWhenFocusTarget(false);
        cedit.add(phsex1);
        phsex1.setBounds(270, 260, 80, 20);

        jLabel23.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 0));
        jLabel23.setText("Phone number             :");
        cedit.add(jLabel23);
        jLabel23.setBounds(100, 300, 130, 22);

        ephone1.setForeground(new java.awt.Color(0, 153, 0));
        ephone1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ephone1.setCaretColor(new java.awt.Color(0, 153, 0));
        cedit.add(ephone1);
        ephone1.setBounds(270, 300, 210, 20);

        update1.setBackground(new java.awt.Color(0, 153, 0));
        update1.setForeground(new java.awt.Color(51, 51, 51));
        update1.setText("SAVE");
        update1.setBorder(null);
        update1.setFocusPainted(false);
        update1.setFocusable(false);
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        cedit.add(update1);
        update1.setBounds(170, 350, 100, 30);

        update3.setBackground(new java.awt.Color(0, 153, 0));
        update3.setForeground(new java.awt.Color(51, 51, 51));
        update3.setText("CLEAR");
        update3.setBorder(null);
        update3.setFocusPainted(false);
        update3.setFocusable(false);
        update3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update3ActionPerformed(evt);
            }
        });
        cedit.add(update3);
        update3.setBounds(380, 350, 100, 30);
        cedit.add(edob1);
        edob1.setBounds(270, 220, 210, 20);

        home.add(cedit, "card3");

        policy.setBackground(new java.awt.Color(255, 255, 255));
        policy.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("POLICY DETAILS");
        jLabel3.setToolTipText("");
        policy.add(jLabel3);
        jLabel3.setBounds(-3, 41, 640, 20);

        pdbox.setBackground(new java.awt.Color(0, 153, 0));
        pdbox.setFocusable(false);
        pdbox.setRequestFocusEnabled(false);
        pdbox.setVerifyInputWhenFocusTarget(false);
        pdbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdboxActionPerformed(evt);
            }
        });
        policy.add(pdbox);
        pdbox.setBounds(260, 110, 110, 20);

        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Select Policy key");
        policy.add(jLabel25);
        jLabel25.setBounds(260, 84, 110, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 0));
        jLabel26.setText("Premium             :");
        policy.add(jLabel26);
        jLabel26.setBounds(140, 270, 110, 20);

        pdpremium.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pdpremium.setForeground(new java.awt.Color(0, 153, 0));
        policy.add(pdpremium);
        pdpremium.setBounds(370, 270, 80, 20);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 0));
        jLabel28.setText("Claimant Name     :");
        policy.add(jLabel28);
        jLabel28.setBounds(140, 320, 110, 20);

        pdcname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pdcname.setForeground(new java.awt.Color(0, 153, 0));
        policy.add(pdcname);
        pdcname.setBounds(370, 320, 80, 20);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 0));
        jLabel30.setText("Policy Key            :");
        policy.add(jLabel30);
        jLabel30.setBounds(140, 180, 110, 20);

        pdkey.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pdkey.setForeground(new java.awt.Color(0, 153, 0));
        policy.add(pdkey);
        pdkey.setBounds(370, 180, 80, 20);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 153, 0));
        jLabel32.setText("Type                  :");
        policy.add(jLabel32);
        jLabel32.setBounds(140, 220, 110, 20);

        pdtype.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pdtype.setForeground(new java.awt.Color(0, 153, 0));
        policy.add(pdtype);
        pdtype.setBounds(370, 220, 80, 20);

        home.add(policy, "card3");

        changepass.setBackground(new java.awt.Color(255, 255, 255));
        changepass.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Re-type password");
        changepass.add(jLabel4);
        jLabel4.setBounds(227, 170, 190, 29);

        newpass.setForeground(new java.awt.Color(0, 153, 0));
        newpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        newpass.setCaretColor(new java.awt.Color(0, 153, 0));
        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        changepass.add(newpass);
        newpass.setBounds(227, 119, 190, 33);

        jLabel24.setForeground(new java.awt.Color(0, 153, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("New Password");
        changepass.add(jLabel24);
        jLabel24.setBounds(220, 90, 190, 29);

        newcpass1.setForeground(new java.awt.Color(0, 153, 0));
        newcpass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        newcpass1.setCaretColor(new java.awt.Color(0, 153, 0));
        changepass.add(newcpass1);
        newcpass1.setBounds(230, 200, 190, 33);

        creset.setBackground(new java.awt.Color(0, 153, 0));
        creset.setForeground(new java.awt.Color(51, 51, 51));
        creset.setText("CHANGE");
        creset.setBorder(null);
        creset.setFocusPainted(false);
        creset.setFocusable(false);
        creset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cresetActionPerformed(evt);
            }
        });
        changepass.add(creset);
        creset.setBounds(140, 300, 146, 37);

        creset1.setBackground(new java.awt.Color(0, 153, 0));
        creset1.setForeground(new java.awt.Color(51, 51, 51));
        creset1.setText("CLEAR");
        creset1.setBorder(null);
        creset1.setFocusPainted(false);
        creset1.setFocusable(false);
        creset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creset1ActionPerformed(evt);
            }
        });
        changepass.add(creset1);
        creset1.setBounds(370, 300, 146, 37);

        cerror.setForeground(new java.awt.Color(255, 0, 0));
        cerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changepass.add(cerror);
        cerror.setBounds(0, 254, 640, 30);

        home.add(changepass, "card3");

        jPanel3.add(home);
        home.setBounds(200, 100, 640, 410);

        min.setBackground(new java.awt.Color(255, 255, 255));
        min.setForeground(new java.awt.Color(153, 153, 153));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });

        mini3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mini3.setForeground(new java.awt.Color(153, 153, 153));
        mini3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini3.setText("-");
        mini3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mini3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mini3MouseExited(evt);
            }
        });
        min.add(mini3);

        jPanel3.add(min);
        min.setBounds(780, 0, 30, 30);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        exit3.setBackground(new java.awt.Color(255, 255, 255));
        exit3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit3.setForeground(new java.awt.Color(153, 153, 153));
        exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit3MouseExited(evt);
            }
        });
        exit.add(exit3);

        jPanel3.add(exit);
        exit.setBounds(810, 0, 30, 30);

        signout.setBackground(new java.awt.Color(0, 153, 0));
        signout.setForeground(new java.awt.Color(51, 51, 51));
        signout.setText("Sign Out");
        signout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        signout.setFocusPainted(false);
        signout.setFocusable(false);
        signout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signout.setRequestFocusEnabled(false);
        signout.setRolloverEnabled(false);
        signout.setVerifyInputWhenFocusTarget(false);
        signout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        jPanel3.add(signout);
        signout.setBounds(730, 40, 80, 30);

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Home Page-20.png"))); // NOI18N
        jButton2.setText("Home");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        jButton2.setVerifyInputWhenFocusTarget(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(40, 40, 110, 30);

        cpassword.setBackground(new java.awt.Color(255, 255, 255));
        cpassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cpassword.setForeground(new java.awt.Color(102, 102, 102));
        cpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Password Reset-20.png"))); // NOI18N
        cpassword.setText(" CHANGE PASSWORD");
        cpassword.setBorderPainted(false);
        cpassword.setFocusPainted(false);
        cpassword.setFocusable(false);
        cpassword.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        cpassword.setMargin(new java.awt.Insets(2, 20, 2, 0));
        cpassword.setRequestFocusEnabled(false);
        cpassword.setRolloverEnabled(false);
        cpassword.setVerifyInputWhenFocusTarget(false);
        cpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cpasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cpasswordMouseExited(evt);
            }
        });
        cpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpasswordActionPerformed(evt);
            }
        });
        jPanel3.add(cpassword);
        cpassword.setBounds(0, 300, 200, 50);

        bpolicy.setBackground(new java.awt.Color(255, 255, 255));
        bpolicy.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bpolicy.setForeground(new java.awt.Color(102, 102, 102));
        bpolicy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-List View-15.png"))); // NOI18N
        bpolicy.setText(" POLICIES");
        bpolicy.setBorderPainted(false);
        bpolicy.setFocusPainted(false);
        bpolicy.setFocusable(false);
        bpolicy.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bpolicy.setMargin(new java.awt.Insets(2, 20, 2, 14));
        bpolicy.setRequestFocusEnabled(false);
        bpolicy.setRolloverEnabled(false);
        bpolicy.setVerifyInputWhenFocusTarget(false);
        bpolicy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bpolicyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bpolicyMouseExited(evt);
            }
        });
        bpolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpolicyActionPerformed(evt);
            }
        });
        jPanel3.add(bpolicy);
        bpolicy.setBounds(0, 250, 200, 50);

        bcedit.setBackground(new java.awt.Color(255, 255, 255));
        bcedit.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bcedit.setForeground(new java.awt.Color(102, 102, 102));
        bcedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Edit File-20.png"))); // NOI18N
        bcedit.setText(" ADD/EDIT CLAIMANT INFO");
        bcedit.setBorderPainted(false);
        bcedit.setFocusPainted(false);
        bcedit.setFocusable(false);
        bcedit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bcedit.setMargin(new java.awt.Insets(2, 20, 2, 14));
        bcedit.setRequestFocusEnabled(false);
        bcedit.setRolloverEnabled(false);
        bcedit.setVerifyInputWhenFocusTarget(false);
        bcedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bceditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bceditMouseExited(evt);
            }
        });
        bcedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bceditActionPerformed(evt);
            }
        });
        jPanel3.add(bcedit);
        bcedit.setBounds(0, 200, 200, 50);

        bphedit.setBackground(new java.awt.Color(255, 255, 255));
        bphedit.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bphedit.setForeground(new java.awt.Color(102, 102, 102));
        bphedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Edit File-20.png"))); // NOI18N
        bphedit.setText(" EDIT INFO");
        bphedit.setBorderPainted(false);
        bphedit.setFocusPainted(false);
        bphedit.setFocusable(false);
        bphedit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bphedit.setMargin(new java.awt.Insets(2, 20, 2, 14));
        bphedit.setRequestFocusEnabled(false);
        bphedit.setRolloverEnabled(false);
        bphedit.setVerifyInputWhenFocusTarget(false);
        bphedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bpheditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bpheditMouseExited(evt);
            }
        });
        bphedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpheditActionPerformed(evt);
            }
        });
        jPanel3.add(bphedit);
        bphedit.setBounds(0, 150, 200, 50);

        binfo.setBackground(new java.awt.Color(255, 255, 255));
        binfo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        binfo.setForeground(new java.awt.Color(102, 102, 102));
        binfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/icons8-Info-20.png"))); // NOI18N
        binfo.setText(" INFO");
        binfo.setBorderPainted(false);
        binfo.setFocusPainted(false);
        binfo.setFocusable(false);
        binfo.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        binfo.setMargin(new java.awt.Insets(2, 20, 2, 14));
        binfo.setRequestFocusEnabled(false);
        binfo.setRolloverEnabled(false);
        binfo.setVerifyInputWhenFocusTarget(false);
        binfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                binfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                binfoMouseExited(evt);
            }
        });
        binfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binfoActionPerformed(evt);
            }
        });
        jPanel3.add(binfo);
        binfo.setBounds(0, 100, 200, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 840, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mini3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseClicked
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_mini3MouseClicked

    private void mini3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseEntered
        min.setBackground(Color.LIGHT_GRAY);
        mini3.setForeground(Color.BLACK);
    }//GEN-LAST:event_mini3MouseEntered

    private void mini3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseExited
        min.setBackground(Color.WHITE);
        mini3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_mini3MouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        min.setBackground(Color.LIGHT_GRAY);
        mini3.setForeground(Color.BLACK);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        min.setBackground(Color.WHITE);
        mini3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_minMouseExited

    private void exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit3MouseClicked

    private void exit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseEntered
        exit.setBackground(Color.RED);
        exit3.setForeground(Color.WHITE);
    }//GEN-LAST:event_exit3MouseEntered

    private void exit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseExited
        exit.setBackground(Color.WHITE);
        exit3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_exit3MouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.RED);
        exit3.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(Color.WHITE);
        exit3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_exitMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        pX = evt.getX();
        pY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       setLocation(getLocation().x + evt.getX() - pX,getLocation().y + evt.getY() - pY);
    }//GEN-LAST:event_formMouseDragged

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        Login.main(new String[0]);
        dispose();
    }//GEN-LAST:event_signoutActionPerformed

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        try {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement  pst = conn.prepareStatement("select * from claimant where policykey=?");
            pst.setString(1, (String) jComboBox2.getSelectedItem());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                ename1.setText(rs.getString(3));
                eaddress1.setText(rs.getString(4));
                phsex1.setSelectedItem(rs.getString(7));
                edob1.setDate(rs.getDate(5));
                ephone1.setText(Long.toString(rs.getLong(8)));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void ename1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ename1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ename1ActionPerformed

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        home.removeAll();
        home.add(welcome);
        home.repaint();
        home.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cpasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpasswordMouseEntered
        cpassword.setBackground(Color.lightGray);
    }//GEN-LAST:event_cpasswordMouseEntered

    private void cpasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpasswordMouseExited
        cpassword.setBackground(Color.WHITE);
    }//GEN-LAST:event_cpasswordMouseExited

    private void cpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasswordActionPerformed
        home.removeAll();
        home.add(changepass);
        home.repaint();
        home.revalidate();
        binfo.setForeground(new java.awt.Color(102,102,102));
        bphedit.setForeground(new java.awt.Color(102,102,102));
        bcedit.setForeground(new java.awt.Color(102,102,102));
        cpassword.setForeground(new java.awt.Color(0,153,0));
        bpolicy.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_cpasswordActionPerformed

    private void bpolicyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpolicyMouseEntered
        bpolicy.setBackground(Color.lightGray);
    }//GEN-LAST:event_bpolicyMouseEntered

    private void bpolicyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpolicyMouseExited
        bpolicy.setBackground(Color.WHITE);
    }//GEN-LAST:event_bpolicyMouseExited

    @SuppressWarnings("ConvertToTryWithResources")
    private void bpolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpolicyActionPerformed
        try {
            pdkey.setText("");  
            pdtype.setText("");
            pdpremium.setText("");
            pdcname.setText("");
            home.removeAll();
            home.add(policy);
            home.repaint();
            home.revalidate();
            bphedit.setForeground(new java.awt.Color(102,102,102));
            bcedit.setForeground(new java.awt.Color(102,102,102));
            bpolicy.setForeground(new java.awt.Color(0,153,0));
            binfo.setForeground(new java.awt.Color(102,102,102));
            cpassword.setForeground(new java.awt.Color(102,102,102));
            pdbox.removeAllItems();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("select policykey from insuredby natural join insuredtype where phkey=?");
            pst.setString(1,Login.username.getText());
            ResultSet rs=pst.executeQuery();
            pdbox.addItem("Select");
            while(rs.next()){
                pdbox.addItem(rs.getString(1));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bpolicyActionPerformed

    private void bceditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bceditMouseEntered
        bcedit.setBackground(Color.lightGray);
    }//GEN-LAST:event_bceditMouseEntered

    private void bceditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bceditMouseExited
        bcedit.setBackground(Color.lightGray);
        bcedit.setBackground(Color.WHITE);
    }//GEN-LAST:event_bceditMouseExited

    @SuppressWarnings("ConvertToTryWithResources")
    private void bceditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bceditActionPerformed
        try {
            home.removeAll();
            home.add(cedit);
            home.repaint();
            home.revalidate();
            bphedit.setForeground(new java.awt.Color(102,102,102));
            bcedit.setForeground(new java.awt.Color(0,153,0));
            bpolicy.setForeground(new java.awt.Color(102,102,102));
            binfo.setForeground(new java.awt.Color(102,102,102));
            cpassword.setForeground(new java.awt.Color(102,102,102));
            jComboBox2.removeAllItems();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("select policykey from insuredby natural join insuredtype where phkey=?");
            pst.setString(1,Login.username.getText());
            ResultSet rs=pst.executeQuery();
            jComboBox2.addItem("Select");
            while(rs.next()){
                jComboBox2.addItem(rs.getString(1));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bceditActionPerformed

    private void bpheditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpheditMouseEntered
        bphedit.setBackground(Color.lightGray);
    }//GEN-LAST:event_bpheditMouseEntered

    private void bpheditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpheditMouseExited
        bphedit.setBackground(Color.WHITE);       
    }//GEN-LAST:event_bpheditMouseExited

    @SuppressWarnings("ConvertToTryWithResources")
    private void bpheditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpheditActionPerformed
       try {
            home.removeAll();
            home.add(phedit);
            home.repaint();
            home.revalidate();
            bphedit.setForeground(new java.awt.Color(0,153,0));
            bcedit.setForeground(new java.awt.Color(102,102,102));
            bpolicy.setForeground(new java.awt.Color(102,102,102));
            binfo.setForeground(new java.awt.Color(102,102,102));
            cpassword.setForeground(new java.awt.Color(102,102,102));
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement  pst = conn.prepareStatement("select pname,address,dob,phone from policyholder where phkey=?");
            pst.setString(1,Login.username.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                ename.setText(rs.getString(1));
                eaddress.setText(rs.getString(2));
                edob.setDate(rs.getDate(3));
                ephone.setText(Long.toString(rs.getLong(4)));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bpheditActionPerformed

    private void binfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binfoMouseEntered
        binfo.setBackground(Color.lightGray);
    }//GEN-LAST:event_binfoMouseEntered

    private void binfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binfoMouseExited
        binfo.setBackground(Color.WHITE);
    }//GEN-LAST:event_binfoMouseExited

    @SuppressWarnings("ConvertToTryWithResources")
    private void binfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binfoActionPerformed
        try {
            home.removeAll();
            home.add(info);
            home.repaint();
            home.revalidate();
            bphedit.setForeground(new java.awt.Color(102,102,102));
            bcedit.setForeground(new java.awt.Color(102,102,102));
            bpolicy.setForeground(new java.awt.Color(102,102,102));
            binfo.setForeground(new java.awt.Color(0,153,0));
            cpassword.setForeground(new java.awt.Color(102,102,102));
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement  pst = conn.prepareStatement("select * from policyholder where phkey=?");
            pst.setString(1,Login.username.getText());
            ResultSet rs = pst.executeQuery();
            iphkey.setText(Login.username.getText());
            if(rs.next()){
                iname.setText(rs.getString(2));
                iaddress.setText(rs.getString(3));
                iage.setText(Integer.toString(rs.getInt(4)));
                isex.setText(rs.getString(5));
                SimpleDateFormat sf = new SimpleDateFormat("dd-MMMMMM-yyyy");
                String D = sf.format(rs.getDate(6));
                idob.setText(D);
                iphoneno.setText(Long.toString(rs.getLong(7)));
            }
            pst=conn.prepareStatement("select count(*) from insuredby natural join insuredtype where phkey=?");
            pst.setString(1,Login.username.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                ipolicy.setText(Integer.toString(rs.getInt(1)));
            }
            pst.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_binfoActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("update policyholder set pname=?,address=?,age=?,sex=?,dob=?,phone=? where phkey=?");
            pst.setString(1,ename.getText());
            pst.setString(2,eaddress.getText());
            SimpleDateFormat sf = new SimpleDateFormat("dd-MMMMMM-yyyy");
            String D = sf.format(edob.getDate());
            String arr[] = D.split("-");
            int day = Integer.parseInt(arr[0]);
            Month month = (Month.valueOf(arr[1].toUpperCase()));
            int year = Integer.parseInt(arr[2]);
            LocalDate today = LocalDate.now();
            LocalDate dob = LocalDate.of(year, month, day);
            Period P = Period.between(dob,today);
            pst.setInt(3,P.getYears());
            pst.setString(4, (String) phsex.getSelectedItem());
            pst.setDate(5,new java.sql.Date(sf.parse(D).getTime()));
            pst.setLong(6,Long.parseLong(ephone.getText()));
            pst.setString(7,Login.username.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Sucessfully Updated");
            ename.setText("");
            eaddress.setText("");
            ephone.setText("");
            phsex.setSelectedIndex(0);
            edob.setDate(null);
            pst.close();
            conn.close();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    @SuppressWarnings("ConvertToTryWithResources")
    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        try {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
            PreparedStatement pst = conn.prepareStatement("select policykey,phkey from claimant where phkey=? and policykey=?");
            pst.setString(1,Login.username.getText());
            pst.setString(2, (String) jComboBox2.getSelectedItem());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                   pst = conn.prepareStatement("update claimant set cname=?,address=?,age=?,sex=?,dob=?,phone=? where policykey=?");
            }
            else {
                pst = conn.prepareStatement("insert into claimant(cname,address,age,sex,dob,phone,phkey,policykey) values(?,?,?,?,?,?,?,?)");
            }
            pst.setString(1,ename1.getText());
            pst.setString(2,eaddress1.getText());
            SimpleDateFormat sf = new SimpleDateFormat("dd-MMMMMM-yyyy");
            String D = sf.format(edob1.getDate());
            String arr[] = D.split("-");
            int day = Integer.parseInt(arr[0]);
            Month month = (Month.valueOf(arr[1].toUpperCase()));
            int year = Integer.parseInt(arr[2]);
            LocalDate today = LocalDate.now();
            LocalDate dob = LocalDate.of(year, month, day);
            Period P = Period.between(dob,today);
            pst.setInt(3,P.getYears());
            pst.setString(4, (String) phsex1.getSelectedItem());
            pst.setDate(5,new java.sql.Date(sf.parse(D).getTime()));
            pst.setLong(6,Long.parseLong(ephone1.getText()));
            pst.setString(7,Login.username.getText());
            pst.setString(8, (String) jComboBox2.getSelectedItem());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Sucessfully Updated");
            ename1.setText("");
            eaddress1.setText("");
            ephone1.setText("");
            phsex1.setSelectedIndex(0);
            edob1.setDate(null);
            jComboBox2.setSelectedIndex(0);
            pst.close();
            conn.close();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update1ActionPerformed

    private void update3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update3ActionPerformed
            ename1.setText("");
            eaddress1.setText("");
            ephone1.setText("");
            phsex1.setSelectedIndex(0);
            edob1.setDate(null);
            jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_update3ActionPerformed

    @SuppressWarnings("StringEquality")
    private void cresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cresetActionPerformed
        try {
            if(newpass.getText()!=null || newcpass1.getText()!=null){
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
                PreparedStatement pst = conn.prepareStatement("update policyholder set password=? where phkey=?");
                if(newpass.getText().equals(newcpass1.getText())) {
                    pst.setString(1,newcpass1.getText());
                    pst.setString(2,Login.username.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Password reset sucessfull");
                    newpass.setText("");
                    newcpass1.setText("");
                    pst.close();
                    conn.close();
                }
                else {
                    cerror.setText("Password doesn't match");
                }
            }
            else {
                cerror.setText("Enter password");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cresetActionPerformed

    private void creset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creset1ActionPerformed
        newpass.setText("");
        newcpass1.setText("");
        cerror.setText("");
    }//GEN-LAST:event_creset1ActionPerformed

    private void pdboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdboxActionPerformed
       Connection conn;
       if(pdbox.getSelectedItem()!="Select"){
            try {  
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root",""); 
                PreparedStatement pst = conn.prepareStatement("select policykey,type,premium from insuredby natural join insuredtype where phkey=? and policykey=?"); 
                pst.setString(1,Login.username.getText());
                pst.setString(2, (String) pdbox.getSelectedItem());
                ResultSet rs=pst.executeQuery();
                if(rs.next()) {  
                    pdkey.setText(rs.getString(1));  
                    pdtype.setText(rs.getString(2));
                    pdpremium.setText(rs.getString(3));
                }  
                pst = conn.prepareStatement("select cname from claimant where phkey=? and policykey=?"); 
                pst.setString(1,Login.username.getText());
                pst.setString(2, (String) pdbox.getSelectedItem());
                rs=pst.executeQuery();
                if(rs.next()) {  
                    pdcname.setText(rs.getString(1));  
                }  
            } catch (SQLException ex) {  
                Logger.getLogger(Agent.class.getName()).log(Level.SEVERE, null, ex);  
            } 
       }
       else{
            pdkey.setText("");  
            pdtype.setText("");
            pdpremium.setText("");
            pdcname.setText("");
       }
       
    }//GEN-LAST:event_pdboxActionPerformed

    private void update2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update2ActionPerformed
            ename.setText("");
            eaddress.setText("");
            ephone.setText("");
            phsex.setSelectedIndex(0);
            edob.setDate(null);
    }//GEN-LAST:event_update2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MetroUI".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Client().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcedit;
    private javax.swing.JButton binfo;
    private javax.swing.JButton bphedit;
    private javax.swing.JButton bpolicy;
    private javax.swing.JPanel cedit;
    private javax.swing.JLabel cerror;
    private javax.swing.JPanel changepass;
    private javax.swing.JLabel clname;
    private javax.swing.JButton cpassword;
    private javax.swing.JButton creset;
    private javax.swing.JButton creset1;
    private javax.swing.JTextArea eaddress;
    private javax.swing.JTextArea eaddress1;
    private com.toedter.calendar.JDateChooser edob;
    private com.toedter.calendar.JDateChooser edob1;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField ename1;
    private javax.swing.JTextField ephone;
    private javax.swing.JTextField ephone1;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel exit3;
    private javax.swing.JPanel home;
    private javax.swing.JTextArea iaddress;
    private javax.swing.JLabel iage;
    private javax.swing.JLabel idob;
    private javax.swing.JLabel iname;
    private javax.swing.JPanel info;
    private javax.swing.JLabel iphkey;
    private javax.swing.JLabel iphoneno;
    private javax.swing.JLabel ipolicy;
    private javax.swing.JLabel isex;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel min;
    private javax.swing.JLabel mini3;
    private javax.swing.JPasswordField newcpass1;
    private javax.swing.JTextField newpass;
    private javax.swing.JComboBox<String> pdbox;
    private javax.swing.JLabel pdcname;
    private javax.swing.JLabel pdkey;
    private javax.swing.JLabel pdpremium;
    private javax.swing.JLabel pdtype;
    private javax.swing.JPanel phedit;
    private javax.swing.JComboBox<String> phsex;
    private javax.swing.JComboBox<String> phsex1;
    private javax.swing.JPanel policy;
    private javax.swing.JButton signout;
    private javax.swing.JButton update;
    private javax.swing.JButton update1;
    private javax.swing.JButton update2;
    private javax.swing.JButton update3;
    private javax.swing.JPanel welcome;
    // End of variables declaration//GEN-END:variables
}
