/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Insurance;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author alinb
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int pX,pY; 
    static String user;
    public Login() {
        initComponents(); 
        groupButton( );
        UIManager.put("Button.select",Color.TRANSLUCENT);
        UIManager.put("RadioButton.select",Color.TRANSLUCENT);
        UIManager.put("OptionPane.background",new java.awt.Color(0,153,0));
        UIManager.put("Panel.background",new java.awt.Color(0,153,0));
        UIManager.put("Button.background",Color.BLACK);
        UIManager.put("Button.foreground",new java.awt.Color(0,153,0));
        UIManager.put("Button.focus",Color.BLACK);
    }
    private void groupButton( ) {
        ButtonGroup bg1 = new ButtonGroup( );
        bg1.add(jRadioButton1);
        bg1.add(jRadioButton2);
        bg1.add(jRadioButton3);
        bg1.clearSelection();
    }
    String uname,password1,cuser;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        siginin = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        plabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        min = new javax.swing.JPanel();
        mini3 = new javax.swing.JLabel();
        exit = new javax.swing.JPanel();
        exit3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("1177326-5011.png")));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(838, 511));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(153, 204, 0));
        jPanel2.setFocusable(false);
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 204, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Select User");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 290, 130, 20);

        jLabel2.setBackground(new java.awt.Color(153, 204, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("User ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 100, 130, 20);

        username.setForeground(new java.awt.Color(0, 153, 0));
        username.setBorder(null);
        username.setCaretColor(new java.awt.Color(153, 204, 0));
        username.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        username.setSelectionColor(new java.awt.Color(51, 51, 255));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username);
        username.setBounds(90, 130, 260, 30);

        password.setForeground(new java.awt.Color(0, 153, 0));
        password.setBorder(null);
        password.setCaretColor(new java.awt.Color(153, 204, 0));
        password.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        password.setSelectionColor(new java.awt.Color(51, 51, 255));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password);
        password.setBounds(90, 230, 260, 30);

        jSeparator1.setBackground(new java.awt.Color(0, 153, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(90, 260, 260, 10);

        jSeparator2.setBackground(new java.awt.Color(0, 153, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 153, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(90, 160, 260, 10);

        siginin.setBackground(new java.awt.Color(0, 153, 0));
        siginin.setForeground(new java.awt.Color(51, 51, 51));
        siginin.setText("Sign In");
        siginin.setAutoscrolls(true);
        siginin.setBorder(null);
        siginin.setFocusCycleRoot(true);
        siginin.setFocusPainted(false);
        siginin.setInheritsPopupMenu(true);
        siginin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigininActionPerformed(evt);
            }
        });
        jPanel2.add(siginin);
        siginin.setBounds(90, 410, 110, 30);

        clear.setBackground(new java.awt.Color(0, 153, 0));
        clear.setForeground(new java.awt.Color(51, 51, 51));
        clear.setText("Clear");
        clear.setAutoscrolls(true);
        clear.setBorder(null);
        clear.setFocusCycleRoot(true);
        clear.setFocusPainted(false);
        clear.setFocusable(false);
        clear.setInheritsPopupMenu(true);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear);
        clear.setBounds(290, 410, 110, 30);

        jLabel3.setBackground(new java.awt.Color(153, 204, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 190, 130, 20);

        plabel.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        plabel.setForeground(new java.awt.Color(153, 204, 0));
        plabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(plabel);
        plabel.setBounds(0, 370, 460, 20);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setForeground(new java.awt.Color(0, 153, 0));
        jRadioButton1.setText("Agent");
        jRadioButton1.setBorder(null);
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.setFocusable(false);
        jRadioButton1.setRequestFocusEnabled(false);
        jRadioButton1.setRolloverEnabled(false);
        jRadioButton1.setVerifyInputWhenFocusTarget(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(210, 330, 100, 40);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setForeground(new java.awt.Color(0, 153, 0));
        jRadioButton2.setText("Client");
        jRadioButton2.setBorder(null);
        jRadioButton2.setFocusPainted(false);
        jRadioButton2.setFocusable(false);
        jRadioButton2.setRequestFocusEnabled(false);
        jRadioButton2.setRolloverEnabled(false);
        jRadioButton2.setVerifyInputWhenFocusTarget(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2actionPerfomed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(320, 330, 70, 40);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setForeground(new java.awt.Color(0, 153, 0));
        jRadioButton3.setText("Admin");
        jRadioButton3.setBorder(null);
        jRadioButton3.setFocusPainted(false);
        jRadioButton3.setFocusable(false);
        jRadioButton3.setRequestFocusEnabled(false);
        jRadioButton3.setRolloverEnabled(false);
        jRadioButton3.setVerifyInputWhenFocusTarget(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(90, 330, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Login");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 40, 840, 50);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Insurance/imageedit_1_9893603339.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(450, 150, 380, 220);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Insurance Mangement System");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(440, 370, 400, 40);

        min.setBackground(new java.awt.Color(255, 255, 255));
        min.setForeground(new java.awt.Color(153, 153, 153));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });

        mini3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mini3.setForeground(new java.awt.Color(153, 153, 153));
        mini3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mini3.setText("-");
        mini3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mini3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mini3MouseExited(evt);
            }
        });
        min.add(mini3);

        jPanel2.add(min);
        min.setBounds(780, 0, 30, 30);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        exit3.setBackground(new java.awt.Color(255, 255, 255));
        exit3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit3.setForeground(new java.awt.Color(153, 153, 153));
        exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit3MouseExited(evt);
            }
        });
        exit.add(exit3);
        exit3.getAccessibleContext().setAccessibleDescription("");

        jPanel2.add(exit);
        exit.setBounds(810, 0, 30, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 840, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        uname = username.getText();
        plabel.setText("");
    }//GEN-LAST:event_usernameActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        username.setText("");
        password.setText("");
        plabel.setText("");
        groupButton( );
    }//GEN-LAST:event_clearActionPerformed

    @SuppressWarnings("RedundantStringConstructorCall")
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        password1 = password.getText();
        plabel.setText("");
    }//GEN-LAST:event_passwordActionPerformed

    @SuppressWarnings({"ConvertToTryWithResources", "static-access", "ResultOfObjectAllocationIgnored"})
    private void sigininActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigininActionPerformed
        try{
            if(username.getText()==null || password.getText()==null || cuser==null){
                plabel.setText("Please fill the form");
            }
        }
        catch(NullPointerException e){
            plabel.setText("Please fill the form");            
        }
        if( username.getText().equals("admin") && password.getText().equals("admin") && cuser.equals("Admin")){
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
                Admin.main(new String[0]);
                dispose();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else if(username.getText()!=null && password.getText()!=null && cuser.equals("Agent")){
            try {
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
                PreparedStatement pst = conn.prepareStatement("select aname from agent where agentkey=? and password=?");
                pst.setString(1,username.getText());
                pst.setString(2,password.getText());
                ResultSet rs=pst.executeQuery();
                if(rs.next()){
                    Agent A=new Agent();
                    A.main(new String[0]);
                    user = rs.getString(1);
                    dispose();
                }
                else {
                    plabel.setText("Incorrect username/password");
                }
                pst.close();
                conn.close();                
            } catch (SQLException e) {
               JOptionPane.showMessageDialog(null,e); 
            }
        }
        else if(username.getText()!=null && password.getText()!=null && cuser.equals("Client")){
            try {
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/insurance?zeroDateTimeBehavior=convertToNull","root","");
                PreparedStatement pst = conn.prepareStatement("select pname from policyholder where phkey=? and password=?");
                pst.setString(1,username.getText());
                pst.setString(2,password.getText());
                ResultSet rs=pst.executeQuery();
                if(rs.next()){
                    Client C=new Client();
                    C.main(new String[0]);
                    user = rs.getString(1);
                    dispose();
                }
                else {
                    plabel.setText("Incorrect username/password");
                }
                pst.close();
                conn.close();                
            } catch (SQLException e) {
               JOptionPane.showMessageDialog(null,e);
            }
        }
        else{
            plabel.setText("Incorrect username/password");
        }
    }//GEN-LAST:event_sigininActionPerformed

    private void jRadioButton2actionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2actionPerfomed
        cuser=jRadioButton2.getText();
    }//GEN-LAST:event_jRadioButton2actionPerfomed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        cuser=jRadioButton3.getText();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        cuser=jRadioButton1.getText();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit3MouseClicked

    private void mini3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_mini3MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        pX = evt.getX();
        pY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(getLocation().x + evt.getX() - pX,getLocation().y + evt.getY() - pY);
    }//GEN-LAST:event_formMouseDragged

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        min.setBackground(Color.LIGHT_GRAY);
        mini3.setForeground(Color.BLACK);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        min.setBackground(Color.WHITE);
        mini3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_minMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.RED);
        exit3.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(Color.WHITE);
        exit3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_exitMouseExited

    private void mini3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseEntered
        min.setBackground(Color.LIGHT_GRAY);
        mini3.setForeground(Color.BLACK);
    }//GEN-LAST:event_mini3MouseEntered

    private void mini3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini3MouseExited
        min.setBackground(Color.WHITE);
        mini3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_mini3MouseExited

    private void exit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseEntered
        exit.setBackground(Color.RED);
        exit3.setForeground(Color.WHITE);
    }//GEN-LAST:event_exit3MouseEntered

    private void exit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseExited
        exit.setBackground(Color.WHITE);
        exit3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_exit3MouseExited

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MetroUI".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel exit3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel min;
    private javax.swing.JLabel mini3;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel plabel;
    private javax.swing.JButton siginin;
    public static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
